Repository wecode-bootcamp-korea/50-3rd-ITcat-frontend, pull requests merged in 2023-11, with the labels that each got.

#1 [50기 홍지영] style : 버튼 피드백 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/styles/common.scss
  src/styles/reset.scss
  src/styles/variable.scss
Labels: 멘토 리뷰 요청

#2 [50기 홍지영] style : 피드백 반영
  public/images/visual_01.png
  src/assets/images/iocn/icon_location.png
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
Labels: 멘토 리뷰 요청

#3 [50기 박주희] style: 피드백 반영
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/components/Ordersinfo.jsx
  src/pages/Payment/components/Ordersinfo.scss
Labels: 멘토 리뷰 요청

#6 [50기 홍지영] fix : 버튼 text 수정
  src/components/Button/Button.jsx
Labels: 멘토 리뷰 요청

#5 [50기 홍지영] style : 레이아웃 수정, 공통 컬러 추가
  src/Router.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/Layout.scss
  src/styles/variable.scss
Labels: 멘토 리뷰 요청, 수정 요청

#8 [50기 홍지영] style : container width 수정
  src/components/Layout/Layout.scss
Labels: 멘토 리뷰 요청

#4 [50기 정현용] feat: confilct 수정 및 리뷰 반영
  public/images/backimg.png
  public/images/gitcat.png
  public/images/social.png
  src/components/Button/Button.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#7 [50기 홍지영] fix : datepicker props 추가
  package-lock.json
  package.json
  src/assets/images/icon/icon_location.png
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/components/Datepicker/Datepicker.jsx
  src/pages/Detail/components/Datepicker/Datepicker.scss
Labels: 멘토 리뷰 요청

#13 [50기 홍지영] fix : 피드백 반영
  src/pages/Admin/Admin.jsx
  src/pages/Admin/Admin.scss
  src/pages/Admin/components/Dashboard/Dashboard.jsx
  src/pages/Admin/components/Dashboard/Dashboard.scss
  src/pages/Admin/components/List/List.jsx
  src/pages/Admin/components/List/List.scss
  src/pages/Admin/components/Post/Post.jsx
  src/pages/Admin/components/Post/Post.scss
Labels: 멘토 리뷰 요청

#17 [50기 홍지영] style : 버튼 비활성화 커서 변경
  src/components/Button/Button.scss
Labels: 멘토 리뷰 요청

#16 [50기 홍지영] fix : row 정렬, style 수정
  public/data/seatData.json
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/components/Seat/Seat.jsx
  src/pages/Detail/components/Seat/Seat.scss
Labels: 멘토 리뷰 요청, 리뷰 진행 중

#18 [50기 홍지영] fix : datepicker 시작과 끝 날짜 추가, timepicker 추가
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/components/Datepicker/Datepicker.jsx
  src/pages/Detail/components/Datepicker/Datepicker.scss
Labels: 멘토 리뷰 요청

#20 [50기 홍지영] fix : 카테고리 추가
  src/pages/Admin/components/Post/Post.jsx
Labels: 멘토 리뷰 요청

#14 [50기 정현용] UI: 메인 페이지 UI 1차 구성
  public/images/left_arrow.png
  public/images/right_arrow.png
  public/video/concertsource.mp4
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/pages/Main/MainData/data.js
Labels: 멘토 리뷰 요청, 완료

#12 [50기 박주희] style: 결제 화면 css 수정
  .gitignore
  package-lock.json
  public/data/paymentData.json
  public/images/payment_icon_yellow_small.png
  src/Router.jsx
  src/components/DetailsInfo/DetailsInfo.jsx
  src/components/DetailsInfo/DetailsInfo.scss
  src/config.js
  src/pages/MyPage/MyPage.jsx
  src/pages/Payment/PayCancel.jsx
  src/pages/Payment/PayResult.jsx
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/components/AddPoints/AddPoints.jsx
  src/pages/Payment/components/AddPoints/AddPoints.scss
  src/pages/Payment/components/OrdersInfo.jsx
  src/pages/Payment/components/OrdersInfo.scss
  src/pages/Payment/components/OrdersInfo/OrdersInfo.jsx
  src/pages/Payment/components/OrdersInfo/OrdersInfo.scss
  src/pages/Payment/components/PriceArea/PriceArea.jsx
  src/pages/Payment/components/PriceArea/PriceArea.scss
Labels: 멘토 리뷰 요청

#10 [50기 홍지영] fix : confilict 해결
  src/Router.jsx
  src/config.js
  src/pages/Detail/Detail.jsx
Labels: 멘토 리뷰 요청

#23 [50기 박주희] style: 코드 순서 수정
  public/data/mypageData.json
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.scss
  src/pages/MyPage/components/ProfileEdit.jsx
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.jsx
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.scss
  src/pages/MyPage/components/ProfileImage.scss
  src/pages/MyPage/components/ProfileImage/ProfileImage.jsx
  src/pages/MyPage/components/ProfileImage/ProfileImage.scss
  src/pages/MyPage/components/UserOrders/UserOrders.jsx
  src/pages/MyPage/components/UserOrders/UserOrders.scss
  src/pages/MyPage/components/UserQr/UserQr.jsx
  src/pages/MyPage/components/UserQr/UserQr.scss
Labels: 수정 요청

#15 [50기 정현용] UI : header 기본 구조 + 기능 완성
  src/Router.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
Labels: 완료

#24 [50기 홍지영] feat : 달력 기능 추가
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/components/Datepicker/Datepicker.jsx
  src/pages/Detail/components/Datepicker/Datepicker.scss
Labels: 멘토 리뷰 요청

#22 [50기 홍지영] 상세 페이지 좌석 feature/detai-datepicker-func branch에서 구현
  public/data/seatData.json
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/Seat/Seat.jsx
  src/pages/Detail/components/Seat/Seat.scss
Labels: Conflict 해결 요청

#26 [50기 홍지영] fix : 피드백 반영(disabled 경우 기능이 다른 브랜치에 있어 머지 후 추가 가능)
  src/pages/Detail/components/Seat/Seat.jsx
Labels: 멘토 리뷰 요청

#27 [50기 홍지영] style : ui 수정, 상세 데이터 불러오기 테스트, 결제 기능 추가 예정
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/components/Seat/Seat.jsx
  src/pages/Detail/components/Seat/Seat.scss
Labels: 멘토 리뷰 요청

#19 [50기 정현용] feat: 소셜 로그인 기능 구현 완료 (머지 기원)
  .gitignore
  public/images/kakao_login_large_wide.png
  src/Router.jsx
  src/components/Auth/SocialLogin.jsx
  src/components/Auth/SocialLogin.scss
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/pages/kakao/KaKaoLogin.jsx
Labels: 멘토 리뷰 요청

#30 [50기 박주희] style: 마이페이지 수정
  .gitignore
  public/data/mypageData.json
  public/data/paymentData.json
  src/components/DetailsInfo/DetailsInfo.jsx
  src/config.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.scss
  src/pages/MyPage/components/OrderArea/OrderArea.jsx
  src/pages/MyPage/components/OrderArea/OrderArea.scss
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.jsx
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.scss
  src/pages/MyPage/components/ProfileImage/ProfileImage.jsx
  src/pages/MyPage/components/ProfileImage/ProfileImage.scss
  src/pages/MyPage/components/UserOrders/UserOrders.jsx
  src/pages/MyPage/components/UserOrders/UserOrders.scss
  src/pages/MyPage/components/UserQr/UserQr.jsx
  src/pages/Payment/PayResult.jsx
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/components/OrdersInfo/OrdersInfo.jsx
  src/pages/Payment/components/OrdersInfo/OrdersInfo.scss
  src/pages/Payment/components/PriceArea/PriceArea.jsx
  src/pages/Payment/components/PriceArea/PriceArea.scss
Labels: 멘토 리뷰 요청

#31 [50기 정현용] 저장데이터 관리 수정 및 관련 헤더 내용 수정
  public/images/logo2.png
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/pages/Login/Login.jsx
  src/pages/kakao/KaKaoLogin.jsx
Labels: 멘토 리뷰 요청

#25 [50기 정현용] fix : Link 및 params로 경로 지정 추가
  public/data/itemList.json
  src/Router.jsx
  src/components/Layout/Layout.jsx
  src/config.js
  src/pages/Category/Category.jsx
  src/pages/Category/Category.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/pages/Main/MainData/data.js
Labels: 멘토 리뷰 요청

#21 [50기 홍지영] feat : 추가, 수정 기능 추가 / 출연진, 달력, 시간 이미지 업로드 수정 예정
  src/Router.jsx
  src/config.js
  src/pages/Admin/components/Dashboard/Dashboard.jsx
  src/pages/Admin/components/List/List.jsx
  src/pages/Admin/components/Post/Post.jsx
  src/pages/Admin/components/Post/Post.scss
  src/pages/Detail/Detail.jsx
Labels: 멘토 리뷰 요청

#33 [50기 홍지영] fix : 피드백 반영
  src/pages/Admin/components/Dashboard/Dashboard.jsx
  src/pages/Admin/components/List/List.jsx
  src/pages/Admin/components/Post/Post.jsx
Labels: 멘토 리뷰 요청

#32 [50기 박주희] 병합완료
  src/components/DetailsInfo/DetailsInfo.scss
  src/config.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.scss
  src/pages/MyPage/components/OrderArea/OrderArea.jsx
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.jsx
  src/pages/MyPage/components/ProfileEdit/ProfileEdit.scss
  src/pages/MyPage/components/ProfileImage/ProfileImage.jsx
  src/pages/MyPage/components/UserOrders/UserOrders.jsx
  src/pages/MyPage/components/UserOrders/UserOrders.scss
  src/pages/Payment/Payment.jsx
  src/pages/Payment/components/OrdersInfo/OrdersInfo.jsx
  src/pages/Payment/components/PriceArea/PriceArea.jsx
Labels: 멘토 리뷰 요청

#35 [50기 홍지영] feat : 좌석 disabled 경우 추가
  src/pages/Detail/components/Seat/Seat.jsx
  src/pages/Detail/components/Seat/Seat.scss
Labels: 멘토 리뷰 요청

#34 [50기 홍지영] fix : 관리자 페이지 수정
  src/Router.jsx
  src/pages/Admin/components/Dashboard/Dashboard.jsx
  src/pages/Admin/components/List/List.jsx
  src/pages/Admin/components/Post/Post.jsx
Labels: 멘토 리뷰 요청

#36 [50 기 정현용] 메인페이지 일부 기능 수정 및 ui 수정 머지 기원
  src/components/Header/Header.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/pages/kakao/KaKaoLogin.jsx
Labels: 멘토 리뷰 요청
